export const OPEN_MODAL = 'MODALS/OPEN_MODAL';
export const ALERT = 'MODALS/ALERT';
export const CLOSE_ALERT = 'MODALS/CLOSE_ALERT';
export const CLOSE_MODAL = 'MODALS/CLOSE_MODAL';
export const SHADOW_CURRENT_PAGE = 'MODALS/SHADOW_CURRENT_PAGE'
export const UNSHADOW_CURRENT_PAGE = 'MODALS/UNSHADOW_CURRENT_PAGE'
