export const __SELECT_WORD = "ENGLISH_ARTICLE/__SELECT_WORD"
export const __SELECT_SENTNCE = 'ENGLISH_ARTICLE/__SELECT_SENTNCE';
export const __TRANSLATE_ALL = 'ENGLISH_ARTICLE/__TRANSLATE_ALL';
export const __HIDE_ALL = "ENGLISH_ARTICLE/__HIDE_ALL";
export const __TRANSLATE_SENTENCES = "ENGLISH_ARTICLE/__TRANSLATE_SENTENCE";
export const __HIDE_TRANSLATE = "ENGLISH_ARTICLE/__HIDE_TRANSLATE";
export const __ASYNC_TRANSLATE_WORDS = {
  pending: "ENGLISH_ARTICLE/__TRANSLATE_WORDS_PENDING",
  resolved: "ENGLISH_ARTICLE/__TRANSLATE_WORDS_RESOVLED",
  rejected: "ENGLISH_ARTICLE/__TRANSLATE_WORDS_REJECTED",
}
export const __ASYNC_LOAD_CONTENT = {
  pending: "ENGLISH_ARTICLE/__LOAD_CONTENT_PENDING",
  resolved: "ENGLISH_ARTICLE/__LOAD_CONTENT_RESOVLED",
  rejected: "ENGLISH_ARTICLE/__LOAD_CONTENT_REJECTED",
}
